export const GET_TODOS_PENDING = 'GET_TODOS_PENDING'
export const GET_TODOS_FULLFILED = 'GET_TODOS_FULLFILED'
export const GET_TODOS_REJECTED = 'GET_TODOS_REJECTED'

export const GET_ARCHIVE_TODOS_PENDING = 'GET_ARCHIVE_TODOS_PENDING'
export const GET_ARCHIVE_TODOS_FULLFILED = 'GET_ARCHIVE_TODOS_FULLFILED'
export const GET_ARCHIVE_TODOS_REJECTED = 'GET_ARCHIVE_TODOS_REJECTED'

// export const GET_NOT_ARCHIVE_TODOS_PENDING = 'GET_NOT_ARCHIVE_TODOS_PENDING'
// export const GET_NOT_ARCHIVE_TODOS_FULLFILED = 'GET_NOT_ARCHIVE_TODOS_FULLFILED'
// export const GET_NOT_ARCHIVE_TODOS_REJECTED = 'GET_NOT_ARCHIVE_TODOS_REJECTED'

export const ADD_TODO_PENDING = 'ADD_TODO_PENDING'
export const ADD_TODO_FULLFILED = 'ADD_TODO_FULLFILED'
export const ADD_TODO_REJECTED = 'ADD_TODO_REJECTED'

export const UPDATE_TODO_PENDING = 'UPDATE_TODO_PENDING'
export const UPDATE_TODO_FULLFILED = 'UPDATE_TODO_FULLFILED'
export const UPDATE_TODO_REJECTED = 'UPDATE_TODO_REJECTED'

export const REMOVE_TODO_PENDING = 'REMOVE_TODO_PENDING'
export const REMOVE_TODO_FULLFILED = 'REMOVE_TODO_FULLFILED'
export const REMOVE_TODO_REJECTED = 'REMOVE_TODO_REJECTED'
